In [ ]:
!pip install numpy

In [ ]:
import numpy as np

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

- object : Objek apa pun yang mengekspos metode antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
- dtype  : type data, opsional
- copy   : Opsional. Secara default (True), objek disalin
- order  : C (baris mayor) atau F (utama kolom) atau A (apa saja) (default)
- subok  : Secara default, array yang dikembalikan dipaksa menjadi array kelas dasar. Jika benar, sub-kelas akan diberikan
- ndimin : Menentukan dimensi minimum dari array yang dihasilkan

In [ ]:
# Contoh 1
# Masukkan nilai integer atau nilai dengan tipe data apapun sesuai kebutuhan
arr = np.array([1,2,3])

In [ ]:
print(arr)

[1 2 3]


In [ ]:
arr[2]

3

In [ ]:
# Contoh 2 array 2 dimensi
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


Tipe Data Array

In [ ]:
# contoh 1 array dengan tipe data integer
print(a.dtype)

int64


In [ ]:
# contoh 2 tipe data dengan unicode string
arr_1 = np.array(['rambutan', 'apel', 'jeruk'])
print(arr_1.dtype)
arr_1 = np.array(['r', 'a', 'j'])
print(arr_1.dtype)

<U8
<U1


In [ ]:
#contoh 3 tipe data yang didefinisikan
arr_2 = np.array([1, 2, 3, 4], dtype='S')

print(arr_2)
print(arr_2.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#contoh 4 tipe data yang diubah= konversi integer
arrs = np.array([1.1, 2.1, 3.1])

newarr = arrs.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Membuat array dari existed data (yang sudah ada)

In [ ]:
#konversi list menjadi ndarray

x = [1, 2, 3, 4, 5]
print(type(x))
x = np.asarray(x)
print(x.dtype)
print(x)

<class 'list'>
int64
[1 2 3 4 5]


In [ ]:
# contoh kedua konversi list menjadi array dengan tipe data yang didefinisikan
x = [1, 2, 3, 4, 5]
print(type(x))
x = np.asarray(x, dtype='f')
print(x.dtype)
print(x)

<class 'list'>
float32
[1. 2. 3. 4. 5.]


# Task 1 untuk audience :
- Buat dua variable tuple yang berisi angka
- masukkan dua variable tuple tersebut kedalam variable bertipe data list
- konversi list tersebut menjadi array numpy

In [ ]:
# Isi disini
# Buat dua variable tuple yang berisi angka
x = (1, 2, 3, 4, 5)
y = (6, 7, 8, 9, 10)

# Masukkan dua variable tuple ke dalam list
list_of_tuples = [x, y]

# Konversi list menjadi array numpy
numpy_array = np.array(list_of_tuples)

print("X:", x)
print("Y:", y)
print("List of Variable:", list_of_tuples)
print("Numpy Array:\n", numpy_array)


X: (1, 2, 3, 4, 5)
Y: (6, 7, 8, 9, 10)
List of Variable: [(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)]
Numpy Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Membuat rentang nilai menggunakan numpy (STUDY CASE) :
membuat dataframe menggunakan rentang nilai random dan deterministik



numpy.arange(start, stop, step, dtype)

In [ ]:
z = np.arange(0, 1, 0.1, dtype='f')
x = np.arange(1,11, 1)
y = np.arange(10,20, 1)

In [ ]:
print(z)
print(x)
print(y)

[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'z' : z, 'x' : x, 'y' : y})

z   x   y
0  0.0   1  10
1  0.1   2  11
2  0.2   3  12
3  0.3   4  13
4  0.4   5  14
5  0.5   6  15
6  0.6   7  16
7  0.7   8  17
8  0.8   9  18
9  0.9  10  19

Operasi umum lain di NumPy beserta tugas untuk audience

In [ ]:
#membuat array dengan nilai 1 di numpy
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#membuat array dengan nilai 0 di numpy
x = np.zeros((5,7))
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
x = np.full((3,4), 0.72)
print(x)

[[0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]]


In [ ]:
x = np.random.rand(5,3)
print(x)

[[0.60638544 0.01604787 0.42380413]
 [0.08845875 0.5078161  0.19979482]
 [0.39411911 0.35023249 0.93827345]
 [0.81447921 0.13856989 0.9868695 ]
 [0.61215718 0.61244983 0.20527644]]


In [ ]:
pd.DataFrame(x, columns=['x', 'y', 'z'])

x         y         z
0  0.606385  0.016048  0.423804
1  0.088459  0.507816  0.199795
2  0.394119  0.350232  0.938273
3  0.814479  0.138570  0.986870
4  0.612157  0.612450  0.205276

In [ ]:
# Tugas 1 : Generate random array menggunakan np.random.rand dengan jumlah baris 3 serta jumlah kolom 4 dan masukkan ke dalam dataframe
# Tugas 2 : Generate array dengan nilai satu dan nol yang memiliki baris 5 dan 6 kolom di dua variable berbeda kemudian konversi ke dataframe
#           dan concat keduanya

# Tugas 1
random_array = np.random.rand(3, 4)
df_random = pd.DataFrame(random_array, columns=['A', 'B', 'C', 'D'])
print("DataFrame dari Tugas 1 (Random Array):\n", df_random)

# Tugas 2
array_zeros = np.zeros((5, 6))
array_ones = np.ones((5, 6))

df_zeros = pd.DataFrame(array_zeros, columns=['Z1', 'Z2', 'Z3', 'Z4', 'Z5', 'Z6'])
df_ones = pd.DataFrame(array_ones, columns=['O1', 'O2', 'O3', 'O4', 'O5', 'O6'])

print("\nDataFrame dari Tugas 2 (Array Nol):\n", df_zeros)
print("\nDataFrame dari Tugas 2 (Array Satu):\n", df_ones)

# Menggabungkan kedua dataframe
concatenated_df = pd.concat([df_zeros, df_ones], axis=1)

print("\nDataFrame hasil penggabungan:\n", concatenated_df)


DataFrame dari Tugas 1 (Random Array):
           A         B         C         D
0  0.136145  0.301701  0.458000  0.246797
1  0.032660  0.137547  0.798701  0.184234
2  0.042996  0.708038  0.581881  0.593338

DataFrame dari Tugas 2 (Array Nol):
     Z1   Z2   Z3   Z4   Z5   Z6
0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0

DataFrame dari Tugas 2 (Array Satu):
     O1   O2   O3   O4   O5   O6
0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0

DataFrame hasil penggabungan:
     Z1   Z2   Z3   Z4   Z5   Z6   O1   O2   O3   O4   O5   O6
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0
1  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0
2  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0